francois:
    resource: "@FrancoisBundle/Controller/"
    type:     annotation
    prefix:   /

francois_reservation:
    resource: "@FrancoisBundle/Resources/config/routing/reservation.yml"
    prefix: /reservation


francois_terrain:
    resource: "@FrancoisBundle/Resources/config/routing/terrain.yml"
    prefix:   /terrain


francois_flight:
    resource: "@FrancoisBundle/Resources/config/routing/flight.yml"
    prefix:   /flight

francois_planemodel:
    resource: "@FrancoisBundle/Resources/config/routing/planemodel.yml"
    prefix:   /planemodel