planemodel_index:
    path:     /
    defaults: { _controller: "FrancoisBundle:planeModel:index" }
    methods:  GET

planemodel_show:
    path:     /{id}/show
    defaults: { _controller: "FrancoisBundle:planeModel:show" }
    methods:  GET

planemodel_new:
    path:     /new
    defaults: { _controller: "FrancoisBundle:planeModel:new" }
    methods:  [GET, POST]

planemodel_edit:
    path:     /{id}/edit
    defaults: { _controller: "FrancoisBundle:planeModel:edit" }
    methods:  [GET, POST]

planemodel_delete:
    path:     /{id}/delete
    defaults: { _controller: "FrancoisBundle:planeModel:delete" }
    methods:  DELETE
