FrancoisBundle\Entity\flight:
    type: entity
    table: null
    repositoryClass: FrancoisBundle\Repository\flightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        departure:
            type: string
            length: '4'
        arrival:
            type: string
            length: '4'
        pilot:
            type: string
            length: 255
        freeSeats:
            type: integer
        takeOfTime:
            type: datetime
    lifecycleCallbacks: {  }
