FrancoisBundle\Entity\planeModel:
    type: entity
    table: null
    repositoryClass: FrancoisBundle\Repository\planeModelRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        model:
            type: string
            length: 255
        manufacturer:
            type: string
            length: 255
        cruiseSpeed:
            type: integer
        nbSeats:
            type: integer
        status:
            type: string
            length: 255
    lifecycleCallbacks: {  }
